services:
  fks_engine:
    build:
      context: .
      dockerfile: Dockerfile
    networks: [fks_net]
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import sys; sys.exit(0)'"]
      interval: 45s
      timeout: 5s
      retries: 2
      start_period: 30s

networks:
  fks_net:
    name: fks_net