services:
  fks_engine:
    build:
      context: .
      dockerfile: ../shared/shared_docker/templates/Dockerfile.python
      args:
        SERVICE_NAME: fks-engine
        SERVICE_TYPE: engine
        SERVICE_PORT: 4300
        PYTHON_VERSION: "3.11"
    working_dir: /app/src
    command: ["python", "main.py"]
    environment:
      TZ: America/Toronto
      SERVICE_PORT: 4300
      ENGINE_SERVICE_PORT: 4300
      PYTHONPATH: /app/src
      FKS_SERVICE_NAME: fks-engine
      FKS_SERVICE_TYPE: engine
      FKS_SERVICE_PORT: 4300
    ports:
      - "4300:4300"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/app/logs
    networks: [fks_net]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4300/health || python -c 'import socket; s=socket.socket(); s.settimeout(2); s.connect((\"127.0.0.1\", 4300)); s.close()' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  fks_net:
    name: fks_net